# Generated by Django 5.2.17 on 2026-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
